# Generated by Django 4.1 on 2022-09-10 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_listmodel_slug_tasks_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='description',
        ),
    ]
